# Generated by Django 5.1.1 on 2025-03-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Cliente'), (3, 'Vendedor')], default=2),
        ),
    ]
