# Generated by Django 5.1.6 on 2025-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Muebles'), (2, 'Electrónica'), (3, 'Ropa y Accesorios'), (4, 'Hogar y Jardín')], default=0),
        ),
    ]
