# Generated by Django 5.1.1 on 2025-04-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0006_producto_descuento_producto_marca_producto_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='rating',
        ),
    ]
