# Generated by Django 5.1.6 on 2025-04-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0012_remove_usuario_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad',
        ),
    ]
