# Generated by Django 5.1.1 on 2025-04-08 19:55

import merkachecheres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0014_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='productos/imagenes', validators=[merkachecheres.models.validar_extension_imagen]),
        ),
    ]
